# -*- coding: utf-8 -*-
"""app_inclusão_deficientes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlZ9hi-yYQvb6i_uwOsDZLiydqfmzheR
"""

import os, random, sqlite3, json, pathlib
from datetime import date, timedelta, datetime
from collections import defaultdict

import streamlit as st
from streamlit.components.v1 import html as st_html
import pandas as pd
import altair as alt

BRAND = "FLEX CARE"
TAGLINE = "Inclusão e Acessibilidade"
COR_ESCURA = "#0E3A47"
COR_DESTAQUE = "#2EC4B6"
COR_SUCESSO = "#2E7D32"
COR_ALERTA = "#C62828"
COR_NEUTRA = "#5F6B7A"
BG = "#F7F9FC"
CARD = "#FFFFFF"

LOGO = r""
LOGO_CAMINHO = os.path.join("/content", LOGO) if pathlib.Path("/content").exists() else LOGO

st.set_page_config(page_title=f"{BRAND} • Agendamento", page_icon="🩺", layout="wide")

st.markdown(f"""
<style>
:root {{
  --escura:{COR_ESCURA}; --destaque:{COR_DESTAQUE}; --sucesso:{COR_SUCESSO};
  --alerta:{COR_ALERTA}; --neutra:{COR_NEUTRA}; --bg:{BG}; --card:{CARD};
}}
.banner {{
  background: linear-gradient(90deg, var(--escura), var(--destaque));
  color:#fff; border-radius:14px; padding:16px 22px; margin:10px 0 16px;
}}
.titulo {{ margin:0; font-weight:800; font-size:1.25rem; }}
.subtitulo {{ margin:2px 0 0; opacity:.95; font-size:.95rem; }}
.card {{
  background:var(--card); border:1px solid #E7EEF7; border-radius:12px;
  padding:14px 16px; margin-bottom:10px; box-shadow:0 1px 2px rgba(0,0,0,.04);
}}
.chip {{
  display:inline-block; background:var(--bg); border:1px solid #E7EEF7;
  color:var(--escura); border-radius:999px; padding:2px 8px; margin-right:6px;
  font-size:.78rem; font-weight:600;
}}
.kpi {{
  background:#ffffffa6; border:1px solid #E7EEF7; border-radius:10px;
  padding:10px 12px; text-align:center; backdrop-filter: blur(2px);
}}
.kpi .lbl {{ color:var(--neutra); font-size:.8rem; margin:0; }}
.kpi .val {{ font-size:1.3rem; font-weight:800; margin:2px 0 0; color:var(--escura); }}
.ok {{ color:var(--sucesso); font-weight:700; }}
.warn {{ color:var(--alerta); font-weight:700; }}
.stButton>button {{
  background:var(--escura) !important; color:#fff !important;
  border:none !important; border-radius:10px !important; font-weight:700 !important;
}}
.badge {{
  display:inline-block; padding:2px 8px; border-radius:999px; margin-right:6px;
  border:1px solid #E7EEF7; background:#fff; font-size:.78rem;
}}
.badge.urg1 {{ background:#E3F2FD; }}
.badge.urg2 {{ background:#C8E6C9; }}
.badge.urg3 {{ background:#FFF9C4; }}
.badge.urg4 {{ background:#FFE0B2; }}
.badge.urg5 {{ background:#FFCDD2; }}
</style>
""", unsafe_allow_html=True)

st.markdown("""
<style>
[vw].enabled{ position:fixed !important; right:16px !important; bottom:16px !important; z-index:2147483647 !important; }
[vw-access-button]{ transform:scale(0.95); transform-origin:bottom right; }
</style>
""", unsafe_allow_html=True)

def enable_vlibras():
    st_html("""
    <div id="__vlibras_mount"></div>
    <script>
    (function () {
      function inject(targetWin) {
        var D = targetWin.document;
        if (D.querySelector("#vlibras-root-global")) return;

        var root = D.createElement("div");
        root.id = "vlibras-root-global";
        root.setAttribute("vw", "");
        root.className = "enabled";
        root.style.cssText = "position:fixed;right:16px;bottom:16px;z-index:2147483647";

        var btn = D.createElement("div");
        btn.setAttribute("vw-access-button", "");
        btn.className = "active";

        var wrap = D.createElement("div");
        wrap.setAttribute("vw-plugin-wrapper", "");
        var top = D.createElement("div");
        top.className = "vw-plugin-top-wrapper";
        wrap.appendChild(top);

        root.appendChild(btn);
        root.appendChild(wrap);
        D.body.appendChild(root);

        function start(){ try { new targetWin.VLibras.Widget("https://vlibras.gov.br/app"); } catch(e){} }
        if (!targetWin.VLibras) {
          var s = D.createElement("script");
          s.src = "https://vlibras.gov.br/app/vlibras-plugin.js";
          s.onload = start;
          D.body.appendChild(s);
        } else {
          start();
        }
      }

      var parentWin = null, sameOrigin = false;
      try { parentWin = window.parent || null; sameOrigin = !!parentWin && parentWin.location.origin === window.location.origin; } catch(e) { sameOrigin = false; }

      if (sameOrigin && parentWin) {
        inject(parentWin);
      } else {
        inject(window);
      }
    })();
    </script>
    """, height=180)

def enable_tts_global():
    st_html("""
    <script>
    (function(){
      const RATE = 1.0, PITCH = 1.0;
      const synth = window.speechSynthesis;
      let last = 0;
      function say(txt){
        if(!txt) return;
        const now = Date.now();
        if (now - last < 700) return;
        last = now;
        try{ synth.cancel(); }catch(e){}
        const u = new SpeechSynthesisUtterance((txt||"").trim().slice(0,260));
        u.rate = RATE; u.pitch = PITCH;
        synth.speak(u);
      }
      function pickText(el){
        if(!el) return "";
        const lbl = el.getAttribute && el.getAttribute("aria-label");
        if (lbl && lbl.length > 3) return lbl;
        const holder = el.closest && el.closest("[data-tts]");
        if (holder) {
          const t = holder.getAttribute("aria-label") || holder.innerText || holder.textContent || "";
          if (t && t.length > 3) return t;
        }
        if (/^(BUTTON|INPUT|SELECT|TEXTAREA)$/i.test(el.tagName)){
          let t = (el.innerText||el.value||"").trim();
          if(!t && el.labels && el.labels[0]) t = el.labels[0].innerText;
          return t;
        }
        return "";
      }
      function bind(doc){
        doc.addEventListener("mouseover", (e)=>{ const txt = pickText(e.target); if (txt) say(txt); }, true);
        doc.addEventListener("focusin", (e)=>{ const txt = pickText(e.target); if (txt) say(txt); });
      }
      try {
        if (window.parent && window.parent.document) bind(window.parent.document);
        else bind(document);
      } catch(e){ bind(document); }
    })();
    </script>
    """, height=0)

def tts_texto(txt: str):
    st.markdown(f'<div data-tts="1" aria-label="{txt}">{txt}</div>', unsafe_allow_html=True)

st.sidebar.markdown("### Perfil")
perfil = st.sidebar.selectbox("Selecione o modo", ["Agendamento", "Triagem", "Consulta"])
st.sidebar.markdown("---")
st.sidebar.markdown("### Acessibilidade")
tts_enabled = st.sidebar.checkbox("Leitura por voz ao passar o mouse", value=False)
vlibras_enabled = st.sidebar.checkbox("Ativar VLibras (Libras)", value=False)
font_scale = st.sidebar.slider("Tamanho da fonte", 1.0, 1.6, 1.0, 0.05)

hc_css = f"""
<style>
html, body, [data-testid='stAppViewContainer'] * {{ font-size: {font_scale}rem; line-height:1.35; }}
</style>
"""
st.markdown(hc_css, unsafe_allow_html=True)

c1, c2 = st.columns([1, 5])
with c1:
    if LOGO_CAMINHO and os.path.exists(LOGO_CAMINHO) and os.path.isfile(LOGO_CAMINHO):
        try:
            st.image(LOGO_CAMINHO, use_container_width=True)
        except TypeError:
            st.image(LOGO_CAMINHO, width=180)
with c2:
    st.markdown(
        f"""
        <div class="banner" data-tts="1" aria-label="{BRAND} Agendamento. {TAGLINE}">
          <div class="titulo">{BRAND} • Plataforma</div>
          <div class="subtitulo">{TAGLINE}</div>
        </div>
        """,
        unsafe_allow_html=True,
    )

especialidades = [
    "psiquiatria","fisioterapia","nutricionista","cardiologia","dermatologia",
    "ginecologia","oftalmologia","pediatria","endocrinologia","odontologia"
]
acessibilidades = ["libras", "braille", "locomocao", "cognitiva"]
faixas_horarios = ["07-09", "09-11", "11-13", "13-15", "15-17", "17-19", "19-21"]
tipo_consulta = ["online", "presencial"]
faixa_periodo = {
    "07-09":"manha","09-11":"manha","11-13":"manha","13-15":"tarde","15-17":"tarde","17-19":"noite","19-21":"noite"
}
faixas_pico = ["09-11", "13-15", "15-17"]

medicos = [
    {"nome":"Dra. Ana","esp":{"psiquiatria"},"online":True,"disp":{"07-09","09-11","11-13","13-15","15-17"}},
    {"nome":"Dr. Bruno","esp":{"psiquiatria"},"online":True,"disp":{"11-13","13-15","17-19","19-21"}},
    {"nome":"Dra. Carla","esp":{"cardiologia"},"online":False,"disp":{"09-11","13-15","15-17","17-19"}},
    {"nome":"Dr. Daniel","esp":{"fisioterapia"},"online":True,"disp":{"09-11","11-13","15-17","19-21"}},
    {"nome":"Dra. Elisa","esp":{"nutricionista"},"online":True,"disp":{"09-11","11-13","13-15","15-17"}},
    {"nome":"Dr. Felipe","esp":{"cardiologia"},"online":False,"disp":{"13-15","15-17","17-19"}},
    {"nome":"Dra. Gabriela","esp":{"dermatologia"},"online":True,"disp":{"09-11","11-13","13-15"}},
    {"nome":"Dra. Helena","esp":{"ginecologia"},"online":False,"disp":{"09-11","13-15","15-17","17-19"}},
    {"nome":"Dr. Igor","esp":{"oftalmologia"},"online":True,"disp":{"11-13","13-15","17-19","19-21"}},
    {"nome":"Dra. Juliana","esp":{"pediatria"},"online":True,"disp":{"07-09","09-11","11-13","13-15"}},
    {"nome":"Dr. Kevin","esp":{"endocrinologia"},"online":False,"disp":{"13-15","15-17","17-19"}},
    {"nome":"Dra. Laura","esp":{"odontologia"},"online":True,"disp":{"07-09","09-11","11-13","15-17","19-21"}},
]

recursos_qtd = {
    "07-09":{"libras":2,"braille":1,"locomocao":1,"cognitiva":1},
    "09-11":{"libras":2,"braille":1,"locomocao":1,"cognitiva":1},
    "11-13":{"libras":1,"braille":2,"locomocao":1,"cognitiva":1},
    "13-15":{"libras":2,"braille":1,"locomocao":2,"cognitiva":1},
    "15-17":{"libras":1,"braille":1,"locomocao":2,"cognitiva":1},
    "17-19":{"libras":1,"braille":1,"locomocao":1,"cognitiva":1},
    "19-21":{"libras":2,"braille":1,"locomocao":1,"cognitiva":1},
}
capacidade = {"07-09":5,"09-11":8,"11-13":6,"13-15":7,"15-17":6,"17-19":5,"19-21":5}

PESO_PERIODO = 100
PESO_RECURSO = 100
PESO_ESP = 100
PESO_ONLINE = 40
PESO_OVER = 100
PESO_URGENCIA = 50
PESO_DISP = 200
MAX_ITER = 1000
RESTARTS = 5
SEED = 42

if pathlib.Path("/content").exists():
    default_db = pathlib.Path("/content/app.db")
else:
    repo_root = pathlib.Path(__file__).resolve().parent
    default_db = repo_root / "scheduling.db"

DB_PATH = os.getenv("SCHEDULING_DB_PATH") or str(default_db)

def get_conn():
    return sqlite3.connect(DB_PATH, check_same_thread=False)

def init_db():
    with get_conn() as con:
        cur = con.cursor()
        cur.executescript("""
        PRAGMA foreign_keys = ON;
        CREATE TABLE IF NOT EXISTS patients (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            data TEXT NOT NULL,
            esp TEXT NOT NULL,
            periodo TEXT NOT NULL,
            tipo TEXT NOT NULL,
            urg INTEGER NOT NULL
        );
        CREATE TABLE IF NOT EXISTS patient_access (
            patient_id INTEGER NOT NULL,
            acc TEXT NOT NULL,
            FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS bookings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            patient_id INTEGER NOT NULL,
            data TEXT NOT NULL,
            faixa TEXT NOT NULL,
            doctor_name TEXT NOT NULL,
            warnings TEXT,
            created_at TEXT DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS capacity (
            faixa TEXT PRIMARY KEY,
            capacidade INTEGER NOT NULL
        );
        CREATE TABLE IF NOT EXISTS resources (
            faixa TEXT NOT NULL,
            recurso TEXT NOT NULL,
            qtd INTEGER NOT NULL,
            PRIMARY KEY (faixa, recurso)
        );
        CREATE TABLE IF NOT EXISTS triage (
            patient_id INTEGER PRIMARY KEY,
            age INTEGER,
            sex TEXT,
            pain INTEGER,
            temp REAL,
            hr INTEGER,
            rr INTEGER,
            spo2 INTEGER,
            sbp INTEGER,
            bleeding TEXT,
            consciousness TEXT,
            chest_pain INTEGER,
            dyspnea INTEGER,
            dehydration INTEGER,
            comorb INTEGER,
            pregnancy_wks INTEGER,
            onset_hours INTEGER,
            notes TEXT,
            FOREIGN KEY (patient_id) REFERENCES patients(id) ON DELETE CASCADE
        );
        """)
        con.commit()

def migrate_db():
    with get_conn() as con:
        cur = con.cursor()
        try:
            cur.execute("PRAGMA table_info(triage)")
            cols = [row[1] for row in cur.fetchall()]
            if 'age' not in cols:
                cur.execute("ALTER TABLE triage ADD COLUMN age INTEGER")
            if 'sex' not in cols:
                cur.execute("ALTER TABLE triage ADD COLUMN sex TEXT")
            con.commit()
        except sqlite3.OperationalError:
            pass

def seed_static_if_empty():
    with get_conn() as con:
        cur = con.cursor()
        cur.execute("SELECT COUNT(*) FROM capacity")
        if cur.fetchone()[0] == 0:
            cur.executemany(
                "INSERT INTO capacity (faixa, capacidade) VALUES (?,?)",
                [(f, capacidade[f]) for f in capacidade],
            )
        cur.execute("SELECT COUNT(*) FROM resources")
        if cur.fetchone()[0] == 0:
            rows = []
            for f, recs in recursos_qtd.items():
                for r, q in recs.items():
                    rows.append((f, r, q))
            cur.executemany(
                "INSERT INTO resources (faixa, recurso, qtd) VALUES (?,?,?)",
                rows,
            )
        con.commit()

def add_patient(p, tri=None):
    with get_conn() as con:
        cur = con.cursor()
        cur.execute(
            "INSERT INTO patients (data, esp, periodo, tipo, urg) VALUES (?,?,?,?,?)",
            (p["data"], p["esp"], p["periodo"], p["tipo"], int(p["urg"])),
        )
        pid = cur.lastrowid
        if p.get("acc"):
            cur.executemany(
                "INSERT INTO patient_access (patient_id, acc) VALUES (?,?)",
                [(pid, a) for a in p["acc"]],
            )
        if tri is not None:
            cur.execute(
                """
            INSERT INTO triage (patient_id, age, sex, pain, temp, hr, rr, spo2, sbp, bleeding, consciousness,
                                chest_pain, dyspnea, dehydration, comorb, pregnancy_wks, onset_hours, notes)
            VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
            """,
                (
                    pid,
                    tri.get("age"),
                    tri.get("sex"),
                    tri.get("pain"),
                    tri.get("temp"),
                    tri.get("hr"),
                    tri.get("rr"),
                    tri.get("spo2"),
                    tri.get("sbp"),
                    tri.get("bleeding"),
                    tri.get("consciousness"),
                    int(tri.get("chest_pain", 0)),
                    int(tri.get("dyspnea", 0)),
                    int(tri.get("dehydration", 0)),
                    tri.get("comorb"),
                    tri.get("pregnancy_wks"),
                    tri.get("onset_hours"),
                    tri.get("notes"),
                ),
            )
        con.commit()
    return pid

def list_patients():
    with get_conn() as con:
        cur = con.cursor()
        cur.execute(
            """
        SELECT p.id, p.data, p.esp, p.periodo, p.tipo, p.urg,
               COALESCE(GROUP_CONCAT(pa.acc, ','), '') AS acc_csv
          FROM patients p
          LEFT JOIN patient_access pa ON pa.patient_id = p.id
         GROUP BY p.id
         ORDER BY p.id ASC
        """
        )
        rows = cur.fetchall()
    pacientes = []
    for r in rows:
        acc = [a for a in r[6].split(",") if a] if r[6] else []
        pacientes.append(
            {"id": r[0], "data": r[1], "esp": r[2], "periodo": r[3], "tipo": r[4], "urg": int(r[5]), "acc": acc}
        )
    return pacientes

def triage_map():
    with get_conn() as con:
        df = pd.read_sql_query("SELECT * FROM triage", con, index_col="patient_id")
    return df.to_dict(orient="index")

def clear_patients():
    with get_conn() as con:
        cur = con.cursor()
        cur.execute("DELETE FROM patient_access")
        cur.execute("DELETE FROM triage")
        cur.execute("DELETE FROM patients")
        con.commit()

def save_bookings(pacientes, sol, aloc, faixas, medicos):
    with get_conn() as con:
        cur = con.cursor()
        for i, p in enumerate(pacientes):
            fidx = sol[2 * i]
            midx = sol[2 * i + 1]
            faixa = faixas[fidx]
            doctor_name = medicos[midx]["nome"]
            warnings = json.dumps(aloc.get(i, {}), ensure_ascii=False)
            cur.execute(
                "INSERT INTO bookings (patient_id, data, faixa, doctor_name, warnings) VALUES (?,?,?,?,?)",
                (p["id"], p["data"], faixa, doctor_name, warnings),
            )
        con.commit()

def bookings_df():
    with get_conn() as con:
        return pd.read_sql_query(
            """
            SELECT b.id as agendamento_id, b.data, b.faixa, b.doctor_name,
                   p.id as patient_id, p.esp, p.periodo, p.tipo, p.urg, b.warnings, b.created_at
              FROM bookings b
              JOIN patients p ON p.id = b.patient_id
             ORDER BY b.id DESC
        """,
            con,
        )

def db_stats():
    with get_conn() as con:
        cur = con.cursor()
        cur.execute("SELECT COUNT(*) FROM patients"); n_pat = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM patient_access"); n_acc = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM triage"); n_tri = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM bookings"); n_bok = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM capacity"); n_cap = cur.fetchone()[0]
        cur.execute("SELECT COUNT(*) FROM resources"); n_res = cur.fetchone()[0]
        cur.execute("SELECT COALESCE(MAX(created_at), '') FROM bookings"); last_created = cur.fetchone()[0] or "—"
    return dict(patients=n_pat, access=n_acc, triage=n_tri, bookings=n_bok, capacity=n_cap, resources=n_res, last=last_created)

init_db()
migrate_db()
seed_static_if_empty()

def calc_triage_urg(tri: dict) -> int:
    pain = int(tri.get("pain") or 0)
    temp = float(tri.get("temp") or 0.0)
    hr = int(tri.get("hr") or 0)
    rr = int(tri.get("rr") or 0)
    spo2 = int(tri.get("spo2") or 0)
    sbp = int(tri.get("sbp") or 0)
    bleeding = (tri.get("bleeding") or "nenhum").lower()
    avpu = (tri.get("consciousness") or "alerta").lower()
    chest_pain = bool(int(tri.get("chest_pain") or 0))
    dyspnea = bool(int(tri.get("dyspnea") or 0))
    dehydration = bool(int(tri.get("dehydration") or 0))
    comorb = int(tri.get("comorb") or 0)
    preg_wks = int(tri.get("pregnancy_wks") or 0)
    onset_h = int(tri.get("onset_hours") or 0)
    if avpu in ["dor", "inconsciente"]:
        return 5
    if sbp and sbp < 90:
        return 5
    if rr and (rr < 8 or rr > 30):
        return 5
    if hr and (hr < 40 or hr > 130):
        return 5
    if spo2 and spo2 < 90:
        return 5
    if bleeding == "grave":
        return 5
    if chest_pain and (spo2 < 94 or sbp < 100):
        return 5
    score = 0
    if pain >= 8: score += 2
    elif pain >= 5: score += 1
    if temp >= 39.0: score += 2
    elif temp >= 38.0: score += 1
    elif 0 < temp < 35.0: score += 2
    if hr >= 110: score += 2
    elif hr >= 100: score += 1
    if rr >= 21: score += 2
    elif 0 < rr < 12: score += 2
    if 90 <= spo2 <= 93: score += 2
    elif 94 <= spo2 <= 95: score += 1
    if 90 <= sbp <= 100: score += 2
    elif 101 <= sbp <= 110: score += 1
    if bleeding == "moderado": score += 2
    elif bleeding == "leve": score += 1
    if avpu == "verbal": score += 2
    if chest_pain: score += 2
    if dyspnea: score += 2
    if dehydration: score += 1
    if comorb >= 4: score += 2
    elif comorb >= 2: score += 1
    if preg_wks >= 20: score += 1
    if onset_h <= 4 and (chest_pain or dyspnea or temp >= 39 or pain >= 8):
        score += 1
    if score >= 9: return 4
    if score >= 6: return 3
    if score >= 3: return 2
    return 1

def gerar_sol(pacientes, faixas, medicos, seed=None):
    if seed is not None:
        random.seed(seed)
    sol = []
    for p in pacientes:
        faixas_disp = [f for f in faixas if faixa_periodo[f] == p["periodo"]]
        faixa = random.choice(faixas_disp)
        med_idxs = [i for i, m in enumerate(medicos) if p["esp"] in m["esp"] and faixa in m["disp"]]
        if not med_idxs:
            med_idxs = [i for i, m in enumerate(medicos) if p["esp"] in m["esp"]]
        med = random.choice(med_idxs)
        sol.extend([faixas.index(faixa), med])
    return sol

def gerar_viz(sol, pacientes, medicos, faixas):
    viz = sol[:]
    i = random.randint(0, len(sol) - 1)
    idx = i // 2
    if i % 2 == 0:
        faixas_disp = [f for f in faixas if faixa_periodo[f] == pacientes[idx]["periodo"]]
        nova_faixa = random.choice(faixas_disp)
        viz[i] = faixas.index(nova_faixa)
        midx_atual = viz[2 * idx + 1]
        med_atual = medicos[midx_atual]
        if (nova_faixa not in med_atual["disp"]) or (pacientes[idx]["esp"] not in med_atual["esp"]):
            med_idxs = [
                j for j, m in enumerate(medicos)
                if pacientes[idx]["esp"] in m["esp"] and nova_faixa in m["disp"]
            ]
            if med_idxs:
                viz[2 * idx + 1] = random.choice(med_idxs)
    else:
        faixa_atual = faixas[viz[2 * idx]]
        med_idxs = [
            j for j, m in enumerate(medicos)
            if pacientes[idx]["esp"] in m["esp"] and faixa_atual in m["disp"]
        ]
        if med_idxs:
            viz[i] = random.choice(med_idxs)
    return viz

def calc_custo(sol, pacientes, medicos, faixas):
    custo = 0.0
    pacientes_faixa = defaultdict(int)
    med_faixa = defaultdict(int)
    aloc = {}
    recursos_disp = {f: {r: recursos_qtd[f][r] for r in recursos_qtd[f]} for f in faixas}
    for i, p in enumerate(pacientes):
        fidx = sol[2 * i]
        midx = sol[2 * i + 1]
        faixa = faixas[fidx]
        med = medicos[midx]
        rec_status = {}
        if p["esp"] not in med["esp"]:
            custo += PESO_ESP
        if p["tipo"] == "online" and not med["online"]:
            custo += PESO_ONLINE
        if faixa not in med["disp"]:
            custo += PESO_DISP
            rec_status["aviso_disp"] = "Médico indisponível neste horário"
        pacientes_faixa[faixa] += 1
        if pacientes_faixa[faixa] > capacidade[faixa]:
            custo += PESO_OVER
        for r in p.get("acc", []):
            if recursos_disp[faixa].get(r, 0) > 0:
                rec_status[r] = "disponível"
                recursos_disp[faixa][r] -= 1
            else:
                rec_status[r] = "indisponível"
                custo += PESO_RECURSO
        if faixa_periodo[faixa] != p["periodo"]:
            custo += PESO_PERIODO
        med_faixa[(med["nome"], faixa)] += 1
        if med_faixa[(med["nome"], faixa)] > 1:
            custo += PESO_OVER
            rec_status["aviso_med"] = f"Médico {med['nome']} ocupado"
        custo -= p.get("urg", 1) * (PESO_URGENCIA / 5)
        aloc[i] = rec_status
    cap_restante = {f: capacidade[f] - pacientes_faixa[f] for f in faixas}
    return custo, aloc, recursos_disp, cap_restante

def hill_climb_once(pacientes, medicos, faixas, max_iter=MAX_ITER, seed=None):
    if len(pacientes) == 0:
        return [], 0.0, {}, {}, {}
    sol = gerar_sol(pacientes, faixas, medicos, seed)
    custo, aloc, recursos, cap_restante = calc_custo(sol, pacientes, medicos, faixas)
    for _ in range(max_iter):
        viz = gerar_viz(sol, pacientes, medicos, faixas)
        c, a, r, cap = calc_custo(viz, pacientes, medicos, faixas)
        if c < custo:
            sol, custo, aloc, recursos, cap_restante = viz, c, a, r, cap
    return sol, custo, aloc, recursos, cap_restante

def hill_climb_multi(pacientes, medicos, faixas, max_iter=MAX_ITER, restarts=RESTARTS, base_seed=SEED):
    best = ([], float("inf"), {}, {}, {})
    for k in range(restarts):
        seed = None if base_seed is None else base_seed + k
        sol, custo, aloc, rec, cap = hill_climb_once(
            pacientes, medicos, faixas, max_iter=max_iter, seed=seed
        )
        if custo < best[1]:
            best = (sol, custo, aloc, rec, cap)
    return best

def bookings_on(date_str: str, faixa: str) -> pd.DataFrame:
    with get_conn() as con:
        return pd.read_sql_query(
            """
            SELECT b.*, p.esp, p.tipo, p.periodo
            FROM bookings b JOIN patients p ON p.id=b.patient_id
            WHERE b.data=? AND b.faixa=?
            """,
            con,
            params=[date_str, faixa],
        )

def resources_left(date_str: str, faixa: str) -> dict:
    with get_conn() as con:
        df = pd.read_sql_query(
            """
            SELECT pa.acc
            FROM bookings b
            JOIN patient_access pa ON pa.patient_id=b.patient_id
            WHERE b.data=? AND b.faixa=?
            """,
            con,
            params=[date_str, faixa],
        )
    used = defaultdict(int)
    for _, row in df.iterrows():
        used[row["acc"]] += 1
    left = {r: recursos_qtd[faixa].get(r, 0) - used.get(r, 0) for r in recursos_qtd[faixa].keys()}
    return left

def doctor_free_on(doctor_name: str, date_str: str, faixa: str) -> bool:
    with get_conn() as con:
        cur = con.cursor()
        cur.execute(
            "SELECT COUNT(*) FROM bookings WHERE doctor_name=? AND data=? AND faixa=?",
            (doctor_name, date_str, faixa),
        )
        return cur.fetchone()[0] == 0

def capacity_left_on(date_str: str, faixa: str) -> int:
    with get_conn() as con:
        cur = con.cursor()
        cur.execute(
            "SELECT COUNT(*) FROM bookings WHERE data=? AND faixa=?",
            (date_str, faixa),
        )
        used = cur.fetchone()[0]
    return capacidade[faixa] - used

def available_doctors(esp: str, faixa: str, tipo: str) -> list:
    docs = [m for m in medicos if esp in m["esp"] and faixa in m["disp"]]
    if tipo == "online":
        docs = [m for m in docs if m["online"]]
    return docs

def find_next_slot(esp: str, tipo: str, acc: list, start_date: date, prefer_faixa: str, days_ahead: int = 7):
    for d in range(0, days_ahead + 1):
        dia = (start_date + timedelta(days=d)).isoformat()
        faixas_try = [prefer_faixa] + [f for f in faixas_horarios if f != prefer_faixa]
        for f in faixas_try:
            if capacity_left_on(dia, f) <= 0:
                continue
            left = resources_left(dia, f)
            if any(left.get(r, 0) <= 0 for r in acc):
                continue
            docs = available_doctors(esp, f, tipo)
            free_docs = [m for m in docs if doctor_free_on(m["nome"], dia, f)]
            if free_docs:
                return dia, f, free_docs[0]["nome"]
    return None

if perfil == "Agendamento":
    tts_texto("Agendamento acessível: escolha especialidade, faixa e tipo. Podemos sugerir alternativa se necessário.")
elif perfil == "Triagem":
    tts_texto("Triagem de pronto-socorro: calcule o grau de urgência.")
else:
    tts_texto("Consulta do médico: visualize agenda e detalhes de pacientes.")

if perfil == "Agendamento":
    st.subheader("Agendamento de consulta")
    with st.form("form_agendamento"):
        data_ag = st.date_input("Data", min_value=date.today())
        esp_sel = st.selectbox("Especialidade", especialidades)
        faixa_sel = st.selectbox("Faixa de horário", faixas_horarios)
        tipo_sel = st.radio("Tipo de consulta", tipo_consulta, horizontal=True)
        acc_sel = st.multiselect("Acessibilidades necessárias (opcional)", acessibilidades)
        docs_esp = available_doctors(esp_sel, faixa_sel, tipo_sel)
        nomes_docs = [d["nome"] for d in docs_esp]
        doc_pref = st.selectbox(
            "Médico preferido (opcional)",
            ["Nenhum"] + nomes_docs if nomes_docs else ["Nenhum"],
            index=0,
        )
        confirmar = st.form_submit_button("Agendar")
    if confirmar:
        dia = data_ag.isoformat()
        cap_left = capacity_left_on(dia, faixa_sel)
        res_left = resources_left(dia, faixa_sel)
        docs_ok = available_doctors(esp_sel, faixa_sel, tipo_sel)
        free_docs = [m for m in docs_ok if doctor_free_on(m["nome"], dia, faixa_sel)]
        chosen_doc = None
        if doc_pref != "Nenhum":
            if any(m["nome"] == doc_pref for m in free_docs) and all(res_left.get(r, 0) > 0 for r in acc_sel) and cap_left > 0:
                chosen_doc = doc_pref
        if chosen_doc is None and free_docs and all(res_left.get(r, 0) > 0 for r in acc_sel) and cap_left > 0:
            chosen_doc = free_docs[0]["nome"]
        if chosen_doc:
            periodo_sel = faixa_periodo[faixa_sel]
            paciente = {
                "data": dia,
                "esp": esp_sel,
                "acc": acc_sel,
                "periodo": periodo_sel,
                "tipo": tipo_sel,
                "urg": 1,
            }
            pid = add_patient(paciente, tri=None)
            with get_conn() as con:
                cur = con.cursor()
                cur.execute(
                    "INSERT INTO bookings (patient_id, data, faixa, doctor_name, warnings) VALUES (?,?,?,?,?)",
                    (pid, dia, faixa_sel, chosen_doc, json.dumps({}, ensure_ascii=False)),
                )
                con.commit()
            st.success(f"Agendado com sucesso: {dia} • {faixa_sel} • {chosen_doc}")
            tts_texto("Agendamento confirmado com sucesso.")
        else:
            sug = find_next_slot(esp_sel, tipo_sel, acc_sel, data_ag, faixa_sel, days_ahead=7)
            if sug:
                dia2, faixa2, doc2 = sug
                st.warning(f"Não foi possível na opção escolhida. Sugestão: {dia2} • {faixa2} com {doc2}.")
                tts_texto("Não foi possível. Sugestão de novo horário disponível exibida.")
            else:
                st.error("Não encontramos alternativa nos próximos 7 dias considerando as restrições informadas.")
                tts_texto("Sem alternativas nos próximos sete dias considerando suas restrições.")

if perfil == "Triagem":
    st.subheader("Triagem de Pronto-Socorro")
    with st.form("form_triagem"):
        col1, col2, col3 = st.columns(3)
        with col1:
            age = st.number_input("Idade (anos)", 0, 120, 35)
            sex = st.selectbox("Sexo", ["F", "M", "Outro"])
            pain = st.slider("Dor (0-10)", 0, 10, 3)
            temp = st.number_input("Temperatura (°C)", 30.0, 43.0, 37.0, step=0.1, format="%.1f")
            hr = st.number_input("Frequência cardíaca (bpm)", 0, 250, 85)
        with col2:
            rr = st.number_input("Frequência respiratória (irpm)", 0, 60, 16)
            spo2 = st.number_input("Saturação O₂ (%)", 0, 100, 97)
            sbp = st.number_input("PA sistólica (mmHg)", 0, 250, 120)
            bleeding = st.selectbox("Sangramento", ["nenhum", "leve", "moderado", "grave"])
            avpu = st.selectbox("Consciência (AVPU)", ["alerta", "verbal", "dor", "inconsciente"])
        with col3:
            chest_pain = st.checkbox("Dor torácica", value=False)
            dyspnea = st.checkbox("Dispneia", value=False)
            dehydration = st.checkbox("Sinais de desidratação", value=False)
            comorb = st.number_input("Nº de comorbidades (0+)", 0, 10, 0)
            pregnancy = st.checkbox("Gestante?", value=False)
            preg_weeks = st.number_input("Semanas de gestação (se aplicável)", 0, 45, 0)
            onset_hours = st.number_input("Horas desde o início dos sintomas", 0, 168, 24)
        notes = st.text_area("Observações (opcional)")
        usar_ml = st.checkbox("Usar modelo ML experimental (fallback para heurística se indisponível)", value=False)
        esp_enc = st.selectbox("Especialidade de encaminhamento (se salvar)", ["pediatria", "cardiologia", "clínico geral", "dermatologia"], index=2)
        salvar = st.checkbox("Salvar caso no banco (como paciente em PS)", value=False)
        enviar = st.form_submit_button("Calcular urgência")
    if enviar:
        tri_dict = dict(
            age=age,
            sex=sex,
            pain=pain,
            temp=temp,
            hr=hr,
            rr=rr,
            spo2=spo2,
            sbp=sbp,
            bleeding=bleeding,
            consciousness=avpu,
            chest_pain=int(chest_pain),
            dyspnea=int(dyspnea),
            dehydration=int(dehydration),
            comorb=comorb,
            pregnancy_wks=(preg_weeks if pregnancy else 0),
            onset_hours=onset_hours,
            notes=notes,
        )
        urg_h = calc_triage_urg(tri_dict)
        urg_final = urg_h
        fonte = "Heurística explicável"
        if usar_ml:
            try:
                from sklearn.tree import DecisionTreeClassifier
                import numpy as np
                def gen_sint(n=2000):
                    xs, ys = [], []
                    for _ in range(n):
                        sample = dict(
                            pain=random.randint(0, 10),
                            temp=round(random.uniform(35.0, 41.5), 1),
                            hr=random.randint(40, 140),
                            rr=random.randint(8, 36),
                            spo2=random.randint(85, 100),
                            sbp=random.randint(80, 160),
                            chest_pain=random.randint(0, 1),
                            dyspnea=random.randint(0, 1),
                            dehydration=random.randint(0, 1),
                            bleeding=random.choice(["nenhum", "leve", "moderado", "grave"]),
                            consciousness=random.choice(["alerta", "verbal", "dor", "inconsciente"]),
                            comorb=random.randint(0, 6),
                            pregnancy_wks=random.choice([0, 10, 25, 35]),
                            onset_hours=random.randint(0, 48),
                        )
                        y = calc_triage_urg(sample)
                        x = [
                            sample["pain"], sample["temp"], sample["hr"], sample["rr"], sample["spo2"], sample["sbp"],
                            sample["chest_pain"], sample["dyspnea"], sample["dehydration"], sample["comorb"], sample["pregnancy_wks"], sample["onset_hours"],
                            ["nenhum", "leve", "moderado", "grave"].index(sample["bleeding"]),
                            ["alerta", "verbal", "dor", "inconsciente"].index(sample["consciousness"]),
                        ]
                        xs.append(x); ys.append(y)
                    return np.array(xs), np.array(ys)
                X, y = gen_sint(2500)
                clf = DecisionTreeClassifier(max_depth=5, random_state=0)
                clf.fit(X, y)
                feat = [
                    tri_dict["pain"], tri_dict["temp"], tri_dict["hr"], tri_dict["rr"], tri_dict["spo2"], tri_dict["sbp"],
                    tri_dict["chest_pain"], tri_dict["dyspnea"], tri_dict["dehydration"], tri_dict["comorb"], tri_dict["pregnancy_wks"], tri_dict["onset_hours"],
                    ["nenhum", "leve", "moderado", "grave"].index(tri_dict["bleeding"]),
                    ["alerta", "verbal", "dor", "inconsciente"].index(tri_dict["consciousness"]),
                ]
                urg_ml = int(clf.predict([feat])[0])
                urg_final = max(urg_h, urg_ml)
                fonte = "Árvore de decisão (ML) + fallback"
            except Exception:
                pass
        st.info(f"Grau de urgência: **{urg_final}/5** ({fonte})")
        if urg_final >= 4:
            st.error("Atendimento prioritário recomendado.")
        elif urg_final == 3:
            st.warning(" Avaliação em breve (prioridade intermediária).")
        else:
            st.success(" Caso não crítico, pode aguardar.")
        tts_texto(f"Urgência calculada: {urg_final} de 5.")
        if salvar:
            dia = date.today().isoformat()
            periodo = faixa_periodo[random.choice(faixas_horarios)]
            paciente = {
                "data": dia,
                "esp": esp_enc if esp_enc != "clínico geral" else "pediatria",
                "acc": [],
                "periodo": periodo,
                "tipo": "presencial",
                "urg": urg_final,
            }
            pid = add_patient(paciente, tri=tri_dict)
            st.success(f"Caso salvo com ID de paciente {pid}.")

if perfil == "Consulta":
    st.subheader("Agenda do médico e prontuário sintético")
    med_nomes = [m["nome"] for m in medicos]
    med_sel = st.selectbox("Médico", med_nomes)
    df_ag = bookings_df()
    df_med = df_ag[df_ag["doctor_name"] == med_sel]
    st.markdown("**Meus agendamentos**")
    st.dataframe(df_med, use_container_width=True)
    if not df_med.empty:
        g_med = (
            df_med.groupby("faixa")["agendamento_id"].count().reindex(faixas_horarios, fill_value=0).reset_index().rename(columns={"agendamento_id": "Qtd"})
        )
        st.altair_chart(
            alt.Chart(g_med).mark_bar().encode(x=alt.X("faixa", sort=faixas_horarios), y="Qtd", tooltip=["faixa", "Qtd"]),
            use_container_width=True,
        )
        st.markdown("---")
        st.markdown("**Detalhes do paciente selecionado**")
        ids = df_med["patient_id"].tolist()
        pid_sel = st.selectbox("Selecione o ID do paciente", ids)
        tri_map_all = triage_map()
        tri_p = tri_map_all.get(int(pid_sel), {})
        colA, colB = st.columns(2)
        with colA:
            st.write("**Sinais vitais e achados**")
            if tri_p:
                vitais = {
                    "Idade": tri_p.get("age"),
                    "Sexo": tri_p.get("sex"),
                    "Dor": tri_p.get("pain"),
                    "Temp (°C)": tri_p.get("temp"),
                    "FC (bpm)": tri_p.get("hr"),
                    "FR (irpm)": tri_p.get("rr"),
                    "SpO₂ (%)": tri_p.get("spo2"),
                    "PAS (mmHg)": tri_p.get("sbp"),
                    "Sangramento": tri_p.get("bleeding"),
                    "Consciência": tri_p.get("consciousness"),
                    "Dor torácica": tri_p.get("chest_pain"),
                    "Dispneia": tri_p.get("dyspnea"),
                    "Desidratação": tri_p.get("dehydration"),
                    "Comorbidades": tri_p.get("comorb"),
                    "Gestação (semanas)": tri_p.get("pregnancy_wks"),
                    "Início (h)": tri_p.get("onset_hours"),
                    "Observações": tri_p.get("notes"),
                }
                st.json(vitais)
            else:
                st.info("Sem triagem cadastrada para este paciente.")
        with colB:
            linha = df_med[df_med["patient_id"] == pid_sel].iloc[0]
            st.write("**Dados do agendamento**")
            st.json(
                {
                    "Data": linha["data"],
                    "Faixa": linha["faixa"],
                    "Especialidade": linha["esp"],
                    "Tipo": linha["tipo"],
                    "Urgência": int(linha["urg"]),
                    "Avisos": json.loads(linha["warnings"]) if linha["warnings"] else {},
                }
            )

st.markdown("---")
st.subheader("Pacientes (todos)")
pacientes_list = list_patients()
tri_map_all = triage_map()
df_p = pd.DataFrame([
    {
        **{k: v for k, v in p.items() if k != "acc"},
        "acc": ", ".join(p.get("acc", [])),
        "pain": tri_map_all.get(p["id"], {}).get("pain"),
        "temp": tri_map_all.get(p["id"], {}).get("temp"),
        "spo2": tri_map_all.get(p["id"], {}).get("spo2"),
        "sbp": tri_map_all.get(p["id"], {}).get("sbp"),
        "hr": tri_map_all.get(p["id"], {}).get("hr"),
        "rr": tri_map_all.get(p["id"], {}).get("rr"),
        "bleeding": tri_map_all.get(p["id"], {}).get("bleeding"),
        "avpu": tri_map_all.get(p["id"], {}).get("consciousness"),
    }
    for p in pacientes_list
])
st.dataframe(df_p, use_container_width=True)

with st.expander("Limpar pacientes (cuidado!)"):
    if st.button("Apagar todos os pacientes"):
        clear_patients()
        st.warning("Pacientes excluídos. Atualize a página para ver a lista vazia.")
        tts_texto("Todos os pacientes foram excluídos")

st.subheader("Agendamentos salvos")
df_b = bookings_df()
st.dataframe(df_b, use_container_width=True)
csv_b = df_b.to_csv(index=False).encode("utf-8")
st.download_button("Baixar agendamentos (CSV)", data=csv_b, file_name="bookings.csv", mime="text/csv")

if not df_b.empty:
    st.subheader("Indicadores agregados (uso de recursos por faixa, por data)")
    with get_conn() as con:
        df_used = pd.read_sql_query(
            """
            SELECT b.data, b.faixa, pa.acc, COUNT(*) as qtd
            FROM bookings b
            JOIN patient_access pa ON pa.patient_id=b.patient_id
            GROUP BY b.data, b.faixa, pa.acc
            """,
            con,
        )
    if not df_used.empty:
        st.dataframe(df_used, use_container_width=True)
        chart = (
            alt.Chart(df_used)
            .mark_bar()
            .encode(x="faixa", y="qtd", color="acc", column="data", tooltip=["data", "faixa", "acc", "qtd"])
        )
        st.altair_chart(chart, use_container_width=True)

st.subheader("Diagnóstico do Banco")
_stats = db_stats()
cA, cB, cC, cD, cE, cF = st.columns(6)
cA.metric("Pacientes", _stats["patients"])
cB.metric("Acessibilidades", _stats["access"])
cC.metric("Triagens", _stats["triage"])
cD.metric("Agendamentos", _stats["bookings"])
cE.metric("Faixas (capacity)", _stats["capacity"])
cF.metric("Recursos", _stats["resources"])
st.caption(f"DB: **{DB_PATH}** • Último agendamento criado em: {_stats['last']}")

if vlibras_enabled:
    enable_vlibras()
    tts_texto("VLibras ativado. Use o botão azul para traduzir para Libras.")

if tts_enabled:
    enable_tts_global()

st.markdown(
    '<div aria-live="polite" id="status-aria" data-tts="1" aria-label="Aplicativo pronto. Use Tab para navegar.">Aplicativo pronto. Use Tab para navegar.</div>',
    unsafe_allow_html=True,
)
